### ISSUE TITLE
No module named 'textspan'

### ISSUE THREAD

**Issue by ChaooMa** [Yinghao-Li/seqlbtoolkit#1]
Get this Error

> Traceback (most recent call last):
  File "bert_train.py", line 21, in <module>
    from end_model.bert.data import BertNERDataset
  File "../end_model/bert/data.py", line 7, in <module>
    from seqlbtoolkit.bert_ner.dataset import BertNERBaseDataset
  File "../seqlbtoolkit/bert_ner/dataset.py", line 15, in <module>
    from ..base.dataset import load_data_from_json, load_data_from_pt
  File "../seqlbtoolkit/base/dataset.py", line 10, in <module>
    from ..data import span_to_label, entity_to_bio_labels, one_hot
  File "../seqlbtoolkit/data.py", line 8, in <module>
    from textspan import align_spans
ModuleNotFoundError: No module named 'textspan'

**Comment by ChaooMa** [comment]
> pip install pytextspan
